addons: {}
after_failure:
- cd $DFB_PROJECT_DIR
- artifacts upload --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket
  $DFB_AWS_BUCKET --target-paths $DFB_AWS_BUILD_PATH $(find . -name '*.log')
after_success:
- cd $DFB_PROJECT_DIR
- export JAVA_TOOL_OPTIONS=-javaagent:$DFB_PROJECT_DIR/jacoco-agent-jdk8.jar=destfile=$DFB_PROJECT_DIR/jacoco.exec
- travis_wait 60 mvn test -Djacoco.skip=true -Dcobertura.skip=true -Dmaven.clover.skip=true
  -Dmaven.javadoc.skip=true -Drat.skip=true -Drat.ignoreErrors=true test-compile
- ./df-build.sh
- cd ${DFB_PROJECT_DIR}
- env > env.file
- echo " ----- Debug info for jacoco and env data -----"
- 'echo "Current dir is: $PWD"'
- 'echo "Env.file: "'
- find . -name 'env.file'
- 'echo "Jacoco cov: "'
- find . -name '*.exec'
- echo " ----------------------------------------------"
- artifacts upload --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket
  $DFB_AWS_BUCKET --target-paths $DFB_AWS_BUILD_PATH $(git ls-files -oi -x *.exec)
- artifacts upload --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket
  $DFB_AWS_BUCKET --target-paths $DFB_AWS_BUILD_PATH ${DFB_PROJECT_DIR}/env.file
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
- wget -O beforebuild.sh $DFB_AGENTS_URL/beforebuild.sh
- chmod a+x beforebuild.sh
- ./beforebuild.sh
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install |
  bash
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: null
  - secure: KxeWqJcvOQ1F5+RIjh0/PJpZZK39A1uysayMB0CuLtBG3JcSwkdF/h0ATxHd/S5xTEX5zqdab48oiQMRoV+SvLV8lC17iOFFA9ZsNkaRnKzSrJCiKI8V43aaRM8nkqSocGp+kmqovOhwOCQiKxcs9eW2RqpzhR4sGiSKRS40madmSr37D4D74F2jrvWaGMcjHKLFmMwyQZdafVIYYebd0rLpyuCTiCstMstOskUjje7k7E+lCmItKSfK9apHkmkN+UXgk+9qChNGzwHRUs6aaRbTvYvWqm+TdRlxJK6k+XyabgMVkSJ9st8Bg/VO+T5FKJPAmicWpr2SX1eM7xr88s+5A0NdHlbcXKFmoRFDm88iWqDq8XNS/7KDDRzdNyKyrTAXWAa17h3lvXvbksgxABlC/N1P6EIk46At7VgVz10oFZ2HJ320yq+zSa5IZTzEhccbl40Qro+u4U1MZPL0tP3I3Uac/px+G5wHgsye1gZBuhHKjMrVoN0OoQoPtN+eFkm2qhGI6R15XnEpq6JyW99VYIZawmV4gC5yCTOv14TWIAZIbSSSvI1oBSw6HVEBE8xAEV4DF7XeOEOv7h22PuYKGasX4dEiFJN1JxS406V3MDURSPy1iyzbENOldAW0Ngwxk9J98+n8k6NijMPi93bR/bgDMTJCFF3+/hbfqdw=
  - secure: aaEQHk7fNh+OsMfCmSTuR2lgBSTJitB9xb9zMDRvSvBQZ4d0oA23UsEKzumUbmZyS8ghMOspneRAthMf3+3HjLn+Da/SCZQ2DThKmMSffhX4H2z6M5Fu7hfEIPfub+q4D2yyqYeQViYDswY5495IpRijvDh1SKSak/4sECyuOHr0bAsJzH73JGIGCHD/FUfh/mlcDrm8Xsuf+kColsb7lPoL2m38GMhoe9kCANzfBWWTpO+y5B/snrkQEFdK7F3m1s8N6vBAKkeJtwKXRghPhwikPP+6xTBk4OXZ9oT7aKO8eocqHKLPOA4RytcrXggU8y5MRwYCWW6AkpwsJ7EmIuPr/zZuNRyNk6UOpu3AXtWOvOfgieUT4U2qtWfDc2d3Uz+QVH0OoPeg3Ya4kbjjJ24kGnX3LzZ1S5ITQUqR+wX+jvCcxUJT55a4+UH3oSA3gwozpavwF1EPUa/cmF4df3QsfHh/FoFTOvDG9fgVN9wHO1P5cZAmxpfi7vYiq796g4oQGp5x967Jy0Z1DHlVKl7kcqJZOTPR/ygkwkde2vi3X/fI6TBw4NNWBbo8h6XD1pxdIp660sc+FbQwCfrQkJwKGHO3JVFvDY0uF2A+7Dy+NrVsa2cgKXNrezwluuLdW77TMdEehMTK67eLdHbgH2kPy1du1ebWbbGMCG8heFI=
  - DFB_PROJECT_DIR=$(pwd)
  - TMP_PROJECT_PARENT_DIR=$(dirname $DFB_PROJECT_DIR)
  - DFB_BUILD_ID=$TRAVIS_BUILD_ID
  - DFB_PRODUCT_NAME=$(basename $DFB_PROJECT_DIR)
  - DFB_OWNER_NAME=$(basename $TMP_PROJECT_PARENT_DIR)
  - DFB_PRODUCT_KEY=${DFB_OWNER_NAME}_${DFB_PRODUCT_NAME}
  - DFB_AWS_BUCKET=aline-external-ci-artifacts
  - DFB_AGENTS_URL=https://s3.amazonaws.com/${DFB_AWS_BUCKET}/agents
  - DFB_PACKAGING_URL=s3://${DFB_AWS_BUCKET}/artifacts/travis/
  - DFB_AWS_BUILD_PATH=/artifacts/travis/${DFB_PRODUCT_KEY}/${DFB_BUILD_ID}/output/
  - AWS_ACCESS_KEY_ID=AKIAIIU2LBOCCKXAIFZQ
  - AWS_SECRET_ACCESS_KEY=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
  - DFB_JTO=-javaagent:${DFB_PROJECT_DIR}/dfbuild-agent.jar=PACKAGING_BASE_URI=$DFB_PACKAGING_URL,PRODUCT_KEY=$DFB_PRODUCT_KEY/,BUILD_KEY=$DFB_BUILD_ID/,MODULES_KEY=modules/,START_TIME=0,BUILD_BASE_DIR=$DFB_PROJECT_DIR
jdk:
- oraclejdk8
language: java
notifications: {}
script:
- export JAVA_TOOL_OPTIONS=$DFB_JTO
- travis_wait 30 mvn -DskipTests=true -Dmaven.javadoc.skip=true -Drat.skip=true -Drat.ignoreErrors=true
  test-compile
# Modified by IntegrationTestInstrumentation at 2016-06-14 20:27:17.303404
